export const accountPaymentAgreementById = (address: string, id: string) => ['account-payment-agreement', address, id]
export const agreementMembersQueryKey = (address: string, id: string) => ['account-payment-agreement-members', address, id]
export const agreementMembershipQueryKey = (address: string, id: string) => ['account-agreement-membership', address, id]
export const accountPaymentAgreementsCreatedQueryKey = (address: string) => ['account-payment-agreements-created', address]
export const accountPaymentAgreementsSignedQueryKey = (address: string) => ['account-payment-agreements-signed', address]
