export const mockSubscriptions = [
    {
        name: "Netflix",
        owner: "id12345id67891id12345id67891",
        benefits: ["Unlimited streaming", "Exclusive content", "Ad-free viewing"],
        description: "Enjoy unlimited streaming of movies and TV shows with Netflix subscription.",
        createdAt: "10/06/2023",
        totalAmount: "12",
        frequency: "Monthly",
        subscriptionCost: "2 EGLD",
        agreementType: {
            receiver: 'owner-address',
            senders: ['sender-one', 'sender-two'],
            frequency: 'M',
            amountType: { amount: 200 },
        },
    },
    {
        name: "Netflix Plus",
        owner: "id22345id78912id12345id67891",
        benefits: ["Listen without ads", "Offline playback", "Unlimited skips"],
        description: "Get access to millions of songs and podcasts without ads with Spotify Premium.",
        createdAt: "10/06/2023",
        totalAmount: "10",
        frequency: "Monthly",
        subscriptionCost: "2 EGLD",
        agreementType: {
            receiver: 'owner-address',
            senders: ['sender-one', 'sender-two'],
            frequency: 'M',
            amountType: { amount: 200 },
        },
    },
    {
        name: "Netflix Pro",
        owner: "id22345id78912id12345id67891",
        benefits: ["Exclusive Disney content", "Multiple streams", "High-quality resolution"],
        description: "Get access to exclusive Disney, Pixar, Marvel, Star Wars, and National Geographic content.",
        createdAt: "10/06/2023",
        totalAmount: "8",
        frequency: "Monthly",
        subscriptionCost: "2 EGLD",
        agreementType: {
            receiver: 'owner-address',
            senders: ['sender-one', 'sender-two'],
            frequency: 'M',
            amountType: { amount: 200 },
        },
    },
];